name: Public NPM package
run-name: Publish NPM package from ${{ github.event.pull_request.base.ref }}

on:
  pull_request:
    types: [closed]
    branches: [develop, master]

permissions:
  contents: write

jobs:
  build-publish:
    name: Build and publish NPM package
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Configure git
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Publish RC version package (develop)
        if: github.event.pull_request.base.ref == 'develop'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          RC_VERSION=$(node -p "require('./package.json').version")
          echo "Creating tag v$RC_VERSION and push to origin"
          git tag v$RC_VERSION
          git push origin v$RC_VERSION

          echo "[JMockver Action - RC] Packaging RC version and publish"
          npm run package
          npm publish --tag rc

      - name: Publish stable version package (master)
        if: github.event.pull_request.base.ref == 'master'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          LOG_PREFIX="[JMockver Action - Stable]"

          echo "$LOG_PREFIX Generating stable version"
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          STABLE_VERSION=$(echo $CURRENT_VERSION | sed 's/-rc\.[0-9]*$//')
          npm version $STABLE_VERSION -m "chore: STABLE package version updated from $CURRENT_VERSION to $STABLE_VERSION"

          echo "$LOG_PREFIX Creating tag v$STABLE_VERSION and push to origin"
          git push --follow-tags

          echo "$LOG_PREFIX Packaging stable version $STABLE_VERSION and publish"
          npm run package
          npm publish

