name: Public NPM package
run-name: Publish NPM package from ${{ github.event.pull_request.base.ref }}

on:
  pull_request:
    types: [closed]
    branches: [develop, master]

jobs:
  build-publish:
    name: Build and publish NPM package
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Update beta version
        if: github.event.pull_request.base.ref == 'develop'
        run: |
          echo "Update beta version"
          npm version prerelease --preid beta --no-git-tag-version

          echo "Packaging"
          npm run package

          echo "Publish beta version"
          npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Remove beta and publish stable version
        if: github.event.pull_request.base.ref == 'master'
        run: |
          echo "Get current version"
          CURRENT_VERSION=$(node -p "require('./package.json').version")

          echo "Remove beta suffix"
          STABLE_VERSION=$(echo $CURRENT_VERSION | sed 's/-beta\.[0-9]*$//')

          echo "Update package.json with stable version"
          npm version $STABLE_VERSION

          echo "Packaging stable version $STABLE_VERSION"
          npm run package

          echo "Publish stable version $STABLE_VERSION"
          npm publish

          echo "Setting git config"
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          echo "Sync develop with master"
          git checkout develop
          git merge master --no-edit
          git push origin develop
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


